Repository TokTok/ci-tools, pull requests merged in 2025-02, with the labels that each got.

#90 feat: Add netlify deploy workflow.
  .github/workflows/netlify.yml
Labels: enhancement

#91 feat: Add install_apple_cert tool to ci-tools scripts.
  scripts/install_apple_cert.sh
Labels: enhancement

#94 feat: Add support for multi-file generic artifacts.
  .github/workflows/deploy-artifact.yml
  tools/rename_artifact.py
Labels: enhancement

#95 feat: Add support for multiple distinct artifacts.
  .github/workflows/deploy-artifact.yml
  tools/artifact_rename.py
  tools/artifact_sha256.py
Labels: enhancement

#96 fix: Support original-only artifact file name globs.
  tools/artifact_rename.py
Labels: bug

#93 feat: Add release workflow.
  .github/keys/iphydf.asc
  .github/workflows/deploy-android.yml
  .github/workflows/deploy-appimage.yml
  .github/workflows/deploy-artifact.yml
  .github/workflows/deploy-flatpak.yml
  .github/workflows/deploy-macos.yml
  .github/workflows/deploy-windows.yml
  .github/workflows/netlify.yml
  .github/workflows/release-deploy.yml
  tools/create_release.py
  tools/create_tarballs.py
  tools/import_developer_keys.sh
  tools/lib/changelog.py
  tools/lib/git.py
  tools/lib/github.py
  tools/lib/stage.py
  tools/sign_release_assets.py
  tools/update_changelog.py
  tools/use_github_actions_identity.sh
Labels: enhancement

#98 test: Add a netlify release test workflow job.
  .github/workflows/draft.yml
Labels: test

#99 fix: Don't try to upload release artifacts on master builds.
  .github/workflows/deploy-macos.yml
Labels: bug

#100 fix: Checkout ci-tools into the correct directory.
  .github/workflows/deploy-artifact.yml
  .netlify/state.json
Labels: bug

#102 fix: Fix screenshotting in appimage build.
  .github/workflows/deploy-appimage.yml
Labels: bug

#103 chore: Add release issue template and workflow.
  .github/ISSUE_TEMPLATE/release.yaml
  .github/workflows/draft.yml
  .github/workflows/release.yml
Labels: chore

#104 chore: Fix release drafter runs aborting each other across PRs.
  .github/workflows/draft.yml
Labels: chore

#105 chore: Limit concurrency by release tracking issue number.
  .github/workflows/release.yml
Labels: chore

#101 feat: Add PR validation to common prepare workflow.
  .clog.toml
  .github/workflows/deploy-prepare.yml
  .github/workflows/release-deploy.yml
  CHANGELOG.md
  tools/add_upstream_remote.sh
  tools/lib/git.py
  tools/use_github_actions_identity.sh
Labels: enhancement

#106 fix: Checkout ci-tools into third_party.
  .github/workflows/release-deploy.yml
Labels: bug

#107 fix: Clear the correct cache on `clear_cache`.
  tools/lib/github.py
Labels: bug

#108 fix: Use the version from the tracking issue if available.
  tools/create_release.py
Labels: bug

#110 fix: Be less qtox-specific.
  tools/validate_pr.py
Labels: bug

#109 feat: Show number of release assets verified in the log.
  tools/create_release.py
  tools/verify_release_assets.py
Labels: enhancement

#111 fix: Verify all assets (except signatures and hashes).
  tools/verify_release_assets.py
Labels: bug

#114 fix: Better detect the project's self-name.
  tools/update_flathub_descriptor_dependencies.py
Labels: bug

#115 fix: Fix self-name detection for real now.
  tools/update_flathub_descriptor_dependencies.py
Labels: bug

#118 fix: Forcibly trigger CI on automation pull requests.
  .github/workflows/release-deploy.yml
  tools/lib/github.py
Labels: bug

#119 chore: Add required secret to release workflow.
  .github/workflows/release.yml
Labels: chore

#121 chore: Add reviewable config.
  .reviewable/completion.js
  .reviewable/settings.yaml
Labels: chore

#122 fix: Reviewable config was broken.
  .reviewable/completion.js
Labels: bug

#123 fix(Security): Don't pass tokens to repo-local code.
  tools/update-versions.sh
  tools/update_flathub_descriptor_dependencies.py
  tools/validate_pr.py
Labels: bug

#112 chore: Add a mypy type check to CI.
  .github/workflows/ci.yml
Labels: chore

#120 cleanup: Add names to all the workflows.
  .github/workflows/check-release.yml
  .github/workflows/common-ci.yml
  .github/workflows/haskell-ci.yml
  .github/workflows/haskell-publish.yml
  .github/workflows/netlify.yml
  .github/workflows/release-deploy.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-soon.yml
Labels: chore, cleanup

#124 fix: Output a zero-length file when changelog is empty.
  tools/update_changelog.py
Labels: bug

#125 fix: Don't run release-soon check on pushes, only pulls.
  .github/workflows/release-soon.yml
Labels: bug

#126 fix: Run release-soon on everything except push.
  .github/workflows/release-soon.yml
Labels: bug

#131 fix: Don't erase release candidate's release notes.
  tools/lib/changelog.py
Labels: bug

#132 chore: Release v0.8.1
  CHANGELOG.md
Labels: chore

#137 docs: Update readme to better reflect what this repo is.
  README.md
  tools/update-versions.sh
Labels: documentation

#133 cleanup: Use ci-tools macos build script.
  .github/workflows/deploy-macos.yml
Labels: cleanup

#135 cleanup: Use ci-tools flatpak builder script.
  .github/workflows/deploy-flatpak.yml
Labels: cleanup

#134 cleanup: Use ci-tools appimage builder script.
  .github/workflows/deploy-appimage.yml
Labels: cleanup

#140 cleanup: Use ci-tools createdmg and gplv3.rtf.
  cmake/Installation.cmake
  platform/flatpak/build.sh
  platform/macos/createdmg
  platform/windows/cross-compile/build.sh
  platform/windows/generate-icon.sh
Labels: cleanup

#142 chore: add my signing key
  .github/keys/Green-Sky.asc
Labels: chore

#144 chore: Release v0.8.2
  CHANGELOG.md
  CMakeLists.txt
  README.md
Labels: chore

#145 fix: Assign issue to release milestone; support gpg args.
  tools/create_release.py
  tools/lib/github.py
  tools/sign_release_assets.py
Labels: bug

#147 feat: Add a script to run bazel builds on circle ci.
  tools/circleci-bazel-test
Labels: enhancement

#148 fix: milestone assignment for rc
  .github/workflows/deploy-flatpak.yml
  tools/create_release.py
Labels: bug

#149 fix: Use "now" as the time stamp for unreleased versions.
  tools/update_changelog.py
Labels: bug

#150 chore: Add bazel test on circleci.
  .circleci/config.yml
  tools/circleci-bazel-test
Labels: chore

#151 perf: Don't run circleci stuff on anything other than PRs.
  tools/circleci-bazel-test
Labels: performance

#152 fix: Add ci-tools to the .gitignore during release.
  tools/create_release.py
Labels: bug

#153 fix: Don't add third_party/.gitignore if it doesn't exist.
  tools/create_release.py
Labels: bug

#154 fix: Correct the android apk artifact names.
  .github/workflows/deploy-android.yml
  .github/workflows/deploy-macos.yml
Labels: bug

#155 feat: Add a standardised flutter workflow.
  .github/workflows/flutter.yml
Labels: enhancement

#156 feat: Add a shared GitHub Pages workflow for flutter apps.
  .github/workflows/flutter-pages.yml
Labels: enhancement

#157 fix: Don't duplicate lines in .gitignore.
  tools/create_release.py
Labels: bug

#158 feat: Add script to update flutter golden images from test failures.
  .github/workflows/flutter.yml
  tools/lib/github.py
  tools/update_goldens.py
Labels: enhancement
